apiVersion: v1
kind: Service
metadata:
  name: qotd-csharp
  labels:
    {{- include "qotd-csharp.labels" . | nindent 4 }}
    app: qotd-csharp
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: qotd-csharp
  type: ClusterIP
